<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/


// require_once('phpmailer/PHPMailerAutoload.php');
// $mail = new PHPMailer;
// $mail->CharSet = 'utf-8';

// $phone = $_POST['user_phone'];

// //$mail->SMTPDebug = 3;									// Enable verbose debug output

// $mail->isSMTP();										// Set mailer to use SMTP
// $mail->Host = 'smtp.mail.ru';							// Specify main and backup SMTP servers
// $mail->SMTPAuth = true;									// Enable SMTP authentication
// $mail->Username = 'aleks.kuzneczov.90@mail.ru';			// Ваш логин от почты с которой будут отправляться письма
// $mail->Password = '41691871xand90';						// Ваш пароль от почты с которой будут отправляться письма
// $mail->SMTPSecure = 'ssl';								// Enable TLS encryption, `ssl` also accepted
// $mail->Port = 465;										// TCP port to connect to / этот порт может отличаться у других провайдеров

// $mail->setFrom('aleks.kuzneczov.90@mail.ru');			// от кого будет уходить письмо?
// $mail->addAddress('lid.konversia@yandex.ru');			// Кому будет уходить письмо 
// //$mail->addAddress('ellen@example.com');				// Name is optional
// //$mail->addReplyTo('info@example.com', 'Information');
// //$mail->addCC('cc@example.com');
// //$mail->addBCC('bcc@example.com');
// //$mail->addAttachment('/var/tmp/file.tar.gz');			// Add attachments
// //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');	// Optional name
// $mail->isHTML(true);									// Set email format to HTML

// $mail->Subject = 'Заявка с тестового сайта';
// $mail->Body    = ' телефон ' .$phone;
// $mail->AltBody = '';

// if(!$mail->send()) {
//     echo 'Error';
// } else {
//     header('location: ../thank-you.html');
// }

if (!empty($_POST['name']) AND !empty($_POST['phone']) AND !empty($_POST['teleg']) AND !empty($_POST['email']) AND !empty($_POST['city']) AND !empty($_POST['age'])){


    $headers = 'From: Brandon\r\n' .
        'Reply-To: brandon1992416@gmail.com\r\n' .
        'X-Mailer: PHP/' . phpversion();

    $theme = 'Новое сообщение';
    $letter .= 'Имя: ' . $_POST['name'] . '\r\n';
    $letter .= 'Телефон: ' . $_POST['phone'] . '\r\n';
    $letter .= 'Телеграм: ' . $_POST['teleg'] . '\r\n';
    $letter .= 'Почта: ' . $_POST['email'] . '\r\n';
    $letter .= 'Город: ' . $_POST['city'] . '\r\n';
    $letter .= 'Возраст: ' . $_POST['age'] . '\r\n';

    if (mail('brandon1992416@gmail.com', $theme, $letter, $headers)) {
        header('location:/');
    } 
};




 //   //Получаем последний компонеет имени загруженного файла
	// $name_of_uploaded_file =
	//     basename($_FILES['uploaded_file']['name']);
	//     // например, index.php
	    
	// //получаем расширение файла (без точки)
	// $type_of_uploaded_file =
	//      substr($name_of_uploaded_file,
	//    // позиция вхождения точки + 1
	//     strrpos($name_of_uploaded_file, '.') + 1);
	// $size_of_uploaded_file =
	//     $_FILES["uploaded_file"]["size"]/1024;
	//     //размер в KBs 

	// //Настройки
	// $max_allowed_file_size = 200; // размер в  KB
	// $allowed_extensions = array(".docx");
	// //Проверки
	// if($size_of_uploaded_file > $max_allowed_file_size )
	// {
	// $errors .= "\n Размер файла должен быть меньше $max_allowed_file_size";
	// }
	// //------ Проверяем расширение файла -----
	// $allowed_ext = false;
	// for($i=0; $i<sizeof($allowed_extensions); $i++)
	// {
	// // сравниваем строки, если = 0, то строки идентичны (без учета регистра)
	//   if(strcasecmp($allowed_extensions[$i],$type_of_uploaded_file) == 0)
	//   {
	//     $allowed_ext = true;
	//   }
	// }
	// if(!$allowed_ext)
	// {
	// $errors .= "\n Расширение файла не соответствует требуемому. ".
	// "Поддерживаются следующие расширения: ".implode(',',$allowed_extensions);
	// }

	// //копируем  временный файл в папку  uploads 

	// $path_of_uploaded_file = $upload_folder . $name_of_uploaded_file;


	// $tmp_path = $_FILES["uploaded_file"]["tmp_name"];


	// // был ли загружен файл при помощи HTTP POST
	// if(is_uploaded_file($tmp_path))
	// {
	// // если файл не скопирован, создаем ошибку
	//   if(!copy($tmp_path,$path_of_uploaded_file))
	//   {
	//     $errors .= '\n error while copying the uploaded file';
	//   }
	// };

	// include_once('Mail.php');
	// include_once('Mail_Mime/mime.php');

	// $message = new Mail_mime();
	// $message->setTXTBody($text);
	// $message->addAttachment($path_of_uploaded_file);
	// $body = $message->get();
	// $extraheaders = array("From"=>$from, 
	//      "Subject"=>$subject,"Reply-To"=>$visitor_email);
	// $headers = $message->headers($extraheaders);
	// $mail = Mail::factory("mail");
	// $mail->send($to, $headers, $body);

?>
